### ISSUE TITLE
How to specify the format_filter for a field to migrate, during Process

### ISSUE THREAD

**Issue by eurecomphil** [evolvingweb/migrate_example_i18n#3]
Hi,

Thanks to your module, I can now migrate D6 pages (just the body) to my D8 with their translation. 

But, my D6 pages have an extra field called "field_context_content" which is a text formatted long field.

When I had inside `migrate_plus.migration.example_hybrid_base.yml` as follows : 
```
process:
  type: constants/node_page
  langcode:
    plugin: default_value
    source: language
    default_value: und
  'body/value': body
  'body/format': constants/body_format
  title: title
  field_context_content:  field_context_content
```
 It works although the context_content field, once migrated, does not know in which format_filter it should appear (in D6 they all are in full_html format).
Do you know how to force full_html format inside the process section here ? 

I tried a lot of format stuff, but I always was unsuccessful.
Thanks again for your help !
